# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  sonarqube:
    working_directory: ~/build
    docker:
      - image: node:20  # Use the official Node.js 20 image
    steps:
      - run: npm install -g sonar-scanner  # Install the SonarQube scanner CLI
      - run: npm -v  # Display the npm version
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: " $SONAR_BRANCH
          echo "Sonar org value is: " $SONAR_ORG
          sonar-scanner \
          -Dsonar.projectKey="SONAR_PROJECT_KEY" \
          -Dsonar.organization="SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."
